export const FETCH_PRODUCTS_DETAIL_PENDING = 'FETCH_PRODUCTS_DETAIL_PENDING';
export const FETCH_PRODUCTS_DETAIL_SUCCESS = 'FETCH_PRODUCTS_DETAIL_SUCCESS';
export const FETCH_PRODUCTS_DETAIL_ERROR = 'FETCH_PRODUCTS_DETAIL_ERROR';